CREATE TABLE CATEGORIAS (
       ID_CATEGORIA NUMBER PRIMARY KEY,
       NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUCTOS_TIENDA (
       ID_PRODUCTO NUMBER PRIMARY KEY,
       NOMBRE VARCHAR2(100) NOT NULL,
       PRECIO NUMBER(10,2) NOT NULL,
       STOCK NUMBER DEFAULT 0,
       ID_CATEGORIA NUMBER,
       FECHA_REGISTRO DATE DEFAULT SYSDATE,
       ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
       CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_CATEGORIA)
              REFERENCES CATEGORIAS(ID_CATEGORIA)
);

INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE) VALUES (1, 'Electrónica');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE) VALUES (2, 'Ropa');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE) VALUES (3, 'Alimentos');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE) VALUES (4, 'Hogar');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE) VALUES (5, 'Juguetes');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (1, 'Laptop Lenovo', 2500.00, 10, 1, 'ACTIVO');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (2, 'Smartphone Samsung', 1500.00, 20, 1, 'ACTIVO');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (3, 'Polera Nike', 120.00, 50, 2, 'ACTIVO');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (4, 'Leche Gloria', 4.50, 200, 3, 'ACTIVO');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (5, 'Silla de madera', 180.00, 15, 4, 'ACTIVO');

INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO)
VALUES (6, 'Rompecabezas 1000 piezas', 65.00, 30, 5, 'ACTIVO');

SELECT * FROM PRODUCTOS_TIENDA;

